name: "Report an issue"
description: "Our tracker for bugs and other issues with the core project"
labels: ["unconfirmed"]
body:
  - type: markdown
    attributes:
     value: "Hey there, thank you for taking the time to submit this issue! Please note that this tracker is only for bugs or other issues with the core project."
  - type: textarea
    attributes:
      label: "The issue"
      description: "Describe your issue in details here. If you can reproduce the issue deterministically, please write a step-by-step guide."
      placeholder: |      
        I tried to do X, but Y happened, and I expected Z. I think this is a bug.

        Here are the steps to reproduce:
        1. run command A
        2. do action B
        3. observe issue
    validations:
      required: true
  - type: input
    attributes:
      label: "Version"
      description: "Please paste the output of `qtile --version` here."
    validations:
      required: true
  - type: dropdown
    attributes:
      label: "Backend"
      description: "On which backend(s) does the issue occur?"
      multiple: true
      options:
        - "X11 (default)"
        - "Wayland (experimental)"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Config"
      description: "If relevant, paste your `~/.config/qtile/config.py` here."
      render: python
  - type: textarea
    attributes:
      label: "Logs"
      description: "You can paste **relevant logs** from `~/.local/share/qtile/qtile.log` here."
      render: text
  - type: checkboxes
    attributes:
      label: "Required"
      options:
        - label: "I have searched past issues to see if this bug has already been reported."
          required: true
        - label: "I've done my very best to help anyone willing to volunteer their time to investigate this problem."
          required: true
